{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
  {{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-{{ $.Values.service.name }}
                port:
                  number: {{ $.Values.ingress.servicePort }}
          {{- end }}
    {{- end }}
  {{- end }}
