apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-nginx-config
data:
  default.conf: |
    server {
        listen 8080 default_server;
        listen [::]:8080 default_server;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ =404;
        }
    }
